# Generated by Django 5.0.1 on 2025-01-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_Token',
            new_name='email_token',
        ),
    ]
