# Generated by Django 5.0.1 on 2025-01-19 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_cart_cart_user'),
        ('products', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.coupon'),
        ),
    ]
