# Generated by Django 5.0.1 on 2025-01-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cart_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Coupon',
            new_name='coupon',
        ),
    ]
