# Generated by Django 5.0.1 on 2025-01-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_coupon_cart_coun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coun',
            new_name='coupon',
        ),
    ]
