# Generated by Django 5.0.1 on 2025-01-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_cart_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
