# Generated by Django 5.0.1 on 2025-01-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_coupon_cart_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupons',
            new_name='coupon',
        ),
    ]
