# Generated by Django 5.0.1 on 2025-01-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_Description',
            new_name='product_description',
        ),
    ]
